/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.gerenciarota.services;

/**
 * Remote interface for GerenciaRotaSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GerenciaRotaSP
   extends javax.ejb.EJBObject
{

   public void finalizaRota( br.com.sankhya.ws.ServiceContext sctx )
      throws java.rmi.RemoteException;

}
