/*
 * Generated by XDoclet - Do not edit!
 */
package br.com.gerenciarota.services;

/**
 * Home interface for GerenciaRotaSP.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface GerenciaRotaSPHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/GerenciaRotaSP";
   public static final String JNDI_NAME="br/com/gerenciarota/services/GerenciaRotaSP";

   public br.com.gerenciarota.services.GerenciaRotaSP create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
