 SELECT
        GRU.CODGRUPOPROD AS ID,
        
              GRU.DESCRGRUPOPROD AS DESCRICAO,
        
              GRU.CODGRUPAI AS ID_DEPARTAMENTO
FROM          TGFGRU GRU 
    INNER JOIN
              TGFGRU PAI 
        ON GRU.CODGRUPAI = PAI.CODGRUPOPROD
WHERE        (GRU.ANALITICO = 'S')