 SELECT
        CODPARC AS ID,
        RAZAOSOCIAL AS RAZAO_SOCIAL,
        CODVEND AS ID_COMPRADOR,
        POTENCIALNEG AS VLR_MIN_COMPRA
FROM          TGFPAR
WHERE        (FORNECEDOR = 'S') 
        AND (CODPARC <> 0)