 SELECT
        
FEMP.CODEMP AS IDFILIAL,
        
EMP.RAZAOSOCIAL AS RAZAO_SOCIAL,
        
EMP.NOMEFANTASIA AS FANTASIA,
        
ENDE.NOMEEND || ' ' || NUMEND AS ENDERECO,
        
CIDE.NOMECID AS CIDADE,
        
UFE.UF AS UF,
        
EMP.CEP AS CEP,
        
EMP.CGC AS CNPJ,
        
EMP.INSCESTAD AS IE,
        
EMP.AD_CODSUFRAMA AS SUFRAMA
FROM TGFEMP FEMP
INNER 
    JOIN
        TSIEMP EMP 
            ON EMP.CODEMP = FEMP.CODEMP 
LEFT  
    JOIN
        TSIEND ENDE 
            ON ENDE.CODEND = EMP.CODEND
LEFT  
    JOIN
        TSICID CIDE 
            ON CIDE.CODCID = EMP.CODCID
LEFT  
    JOIN
        TSIUFS UFE  
            ON UFE.CODUF   = CIDE.UF
WHERE 
    FEMP.AD_USASYSTOCK = 'S'
AND FEMP.ATIVO = 'S'